### ISSUE TITLE
Automate dependency updates

### ISSUE THREAD

**Issue by speedyleion** [speedyleion/sphinx-c-autodoc#20]
With #17 it's apparent that the dependencies need to be managed in a more automated fashion:
- [x] #18 to provide a passing CI.
- [x] #19 
  - [x] ~Need to look at python/pip usage in dependabot doesn't seem to be updating~ It just took longer
- [x] merge dependabot prs
  - [x] ~For some reason sphinx won't go from 4.3.2 to 5.x with dependabot, even though #24 happened~
         I found the issue:
         ```
         Because flake8 (4.0.1) depends on importlib-metadata (<4.3) and sphinx (5.3.0) depends on importlib-metadata (>=4.8), flake8 (4.0.1) is incompatible with sphinx (5.3.0). So, because sphinx-c-autodoc depends on both sphinx (5.3.0) and flake8 (4.0.1), version solving failed.
         ```
- [x] #28 
- [x] add back mypy and pylint to the ci #40 #42
- [x] document deprecation plan.  #43
